### ISSUE TITLE
"invalid byte sequence in US-ASCII" in search

### ISSUE THREAD

**Issue by fns** [lord/alfred-quicknote#1]
Add `Encoding.default_external = Encoding::UTF_8` to the beginning of search.rb to get rid of it.

**Comment by lord** [comment]
Whoa, real people use this extension! :smile: Thanks for the suggestion, I've added it, although probably not going to update the `alfredworkflow` file since honestly I haven't used Alfred in a year and don't really remember how it works.

**Comment by fns** [comment]
No problem - I just changed it on mine :) And BTW thanks for the workflow :)

**Comment by lord** [comment]
Of course!
